% -------------------------------------------------------------------
%  Generated by MATLAB on 17-May-2025 15:32:18
%  MATLAB version: 9.11.0.1769968 (R2021b)
% -------------------------------------------------------------------
saveVarsMat = load('demo1.mat');

A = saveVarsMat.A; % <100x100 double> 元素太多

B = saveVarsMat.B; % <100x100 double> 元素太多

F1 = saveVarsMat.F1; % <100x100 double> 元素太多

F2 = saveVarsMat.F2; % <100x100 double> 元素太多

alpha = 0.7;

beta = 0.3;

original_img = saveVarsMat.original_img; % <2480x3425 uint8> 元素太多

x = saveVarsMat.x; % <100x100 double> 元素太多

y = saveVarsMat.y; % <100x100 double> 元素太多

clear saveVarsMat;
